// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACBSHI59gcTfCX6agyoR1xOeCKj9Ql4rY',
    appId: '1:1008479134217:web:44f6ce11fe6aea81eb8ed8',
    messagingSenderId: '1008479134217',
    projectId: 'healthyfood-fe90c',
    authDomain: 'healthyfood-fe90c.firebaseapp.com',
    storageBucket: 'healthyfood-fe90c.appspot.com',
    measurementId: 'G-CF7XMPKZVT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5nQcI4ZwNJ7jDOb9ma7GLyCI8ZJRA6Bo',
    appId: '1:1008479134217:android:5bb3ff01aaa82f3aeb8ed8',
    messagingSenderId: '1008479134217',
    projectId: 'healthyfood-fe90c',
    storageBucket: 'healthyfood-fe90c.appspot.com',
  );
}
